FROM node:14.21.2 AS build

WORKDIR /agora

# install packages
COPY package*.json ./
RUN npm install

COPY . .

FROM node:14.21.2-alpine

WORKDIR /agora

COPY --from=build /agora .

EXPOSE 8080

CMD [ "npm", "start" ]

#docker buildx build --platform linux/amd64,linux/arm64 -f /Users/gildas/Projects/Djondo/Agora/src/vision-server/DockerFile -t gawesso/agora:1.0.0 . --push

