FROM node:14.21.2 AS build

WORKDIR /agora

# install packages
COPY package*.json ./
RUN npm install

COPY . .

FROM node:14.21.2-slim

WORKDIR /agora

RUN apt-get update && \
    apt-get install -y unoconv libreoffice openjdk-11-jdk-headless --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=build /agora .

RUN mkdir -p /usr/share/fonts/truetype/
RUN install -m644 resources/fonts/*.ttf /usr/share/fonts/truetype/

EXPOSE 8080

CMD [ "npm", "start" ]

#docker buildx build --platform linux/amd64,linux/arm64 -f /Users/gildas/Projects/Djondo/Agora/src/vision-server/DockerFile -t gawesso/agora:1.0.0 . --push

